
// Storage Keys
const STORAGE_KEYS = {
    CURRENT_USER: 'calendar_current_user',
    USERS: 'calendar_users',
    EVENTS: (user) => `calendar_events_${user}`,
    THEME: (user) => `calendar_theme_${user}`,
    BACKGROUND: (user) => `calendar_background_${user}`,
    CALENDARS: (user) => `calendar_calendars_${user}`,
    LOCATION: (user) => `calendar_location_${user}`,
    PRAYER_TIMES_CACHE: (user) => `calendar_prayer_cache_${user}`,
    JOURNAL: (user) => `calendar_journal_${user}`,
    VARIABLES: (user) => `calendar_variables_${user}`,
    SHOW_PRAYER_TIMES: (user) => `calendar_show_prayer_${user}`,
    TASKS: (user) => `calendar_tasks_${user}`,
    FORGOTTEN: (user) => `calendar_forgotten_${user}`,
    RENDER_WINDOW: (user) => `calendar_render_window_${user}`,
    PFP: (user) => `calendar_pfp_${user}`,
    MONTHLY_BG: (user) => `calendar_monthly_bg_${user}`,
    CALENDAR_MODE: (user) => `calendar_mode_${user}`,
    HIJRI_OFFSETS: (user) => `calendar_hijri_offsets_${user}`,
    LANGUAGE:        'calendar_language',
    ALARM_DIFFICULTY: 'uwu_alarm_difficulty',
    ALARM_EQ_COUNT:   'uwu_alarm_eq_count',
    STANDALONE_ALARMS: 'uwu_standalone_alarms',
    ALARM_RINGTONE:   'uwu_alarm_ringtone',
    ALARM_RINGTONE_NAME: 'uwu_alarm_ringtone_name',
    ALARM_SNOOZE_MIN: 'uwu_alarm_snooze_min',
    ALARM_GENTLE_WAKE: 'uwu_alarm_gentle_wake',
    SYNC_CONFIG:     'calendar_sync_config',
    SYNC_META:       'calendar_sync_meta',
    SYNC_STATUS:     'calendar_sync_status',
};

// ═══════════════════════════════════════════
//  INTERNATIONALISATION  (English / Arabic)
// ═══════════════════════════════════════════
const TRANSLATIONS = {
  en: {
    monthNames:      ['January','February','March','April','May','June','July','August','September','October','November','December'],
    monthNamesShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    dayNamesLong:    ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    dayNamesShort:   ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    dayLetters:      ['S','M','T','W','T','F','S'],
    newEvent:        'New Event',
    addCalendar:     'Add Calendar',
    myCalendars:     'My Calendars',
    accountSettings: 'Account & Settings',
    today:           'Today',
    openJournal:     'Open Journal',
    hideJournal:     'Hide Journal',
    journal:         'Journal',
    score:           'Score',
    tasks:           'Tasks',
    day:             'Day',
    week:            'Week',
    threeDays:       '3 Days',
    month:           'Month',
    year:            'Year',
    allTime:         'All-time',
    prayerTimes:     'Prayer Times',
    hidePrayerTimes: 'Hide Prayer Times',
    saveJournal:     'Save Journal',
    saveScore:       'Save Score',
    save:            'Save',
    cancel:          'Cancel',
    delete:          'Delete',
    newTaskPlaceholder: 'New task…',
    allDay:          'All day',
    doesNotRepeat:   'Does not repeat',
    daily:           'Daily',
    weekly:          'Weekly',
    monthly:         'Monthly',
    yearly:          'Yearly',
    weekdays:        'Every weekday (Mon–Fri)',
    custom:          'Custom...',
    add:             'Add',
    profilePicture:  'Profile Picture',
    appearance:      'Appearance & Themes',
    journalVars:     'Journal Variables',
    locationSettings:'Location Settings',
    backgroundImage: 'Background Image',
    renderWindow:    'Event Render Window',
    viewAllTasks:    'View All Tasks',
    forgottenTasks:  'Forgotten Tasks',
    exportJson:      'Export Data (JSON)',
    exportIcs:       'Export to Calendar (.ics)',
    importData:      'Import Data',
    clearData:       'Clear All Data',
    accounts:        'Accounts',
    settings:        'Settings',
    navMenu:         'Menu',
    navAdd:          'Add',
    navPrayer:       'Prayer',
    toHijri:         'Switch to Hijri Calendar',
    toGregorian:     'Switch to Gregorian',
    pts:             'pts',
    writePlaceholder:'Write about your day…',
    titlePlaceholder:'Title (optional)',
    addTitle:        'Add title',
    pointsPlaceholder:'Points (optional)',
    addDescription:  'Add description',
    timeTo:          'to',
    edit:            'Edit',
    close:           'Close',
    contd:           "cont’d",
    usePrayerTimes:  'Use Prayer Times',
    prayerTime:      'Prayer Time',
    startOffset:     'Start Offset (minutes)',
    endOffset:       'End Offset (minutes)',
    switchToArabic:  'العربية',
    switchToEnglish: 'English',
    newCalendar:     'New Calendar',
    editCalendar:    'Edit Calendar',
    editEvent:       'Edit Event',
    deleteCalendar:  'Delete Calendar',
    jumuah:          "Jumu'ah",
    adjusted:        'Adjusted',
    sighting:        'Sighting',
    moonSighting:    'Moon Sighting',
    addAccount:      'Add Account',
    deleteAccount:   'Delete Account',
    upload:          'Upload',
    remove:          'Remove',
    search:          'Search events…',
    variables:       'Variables',
    noneSet:         'none set',
    expression:      'Expression',
    never:           'Never',
    after:           'After',
    onDate:          'On',
    on:              'On',
    times:           'times',
    occurrences:     'occurrences',
    days:            'days',
    weeks:           'weeks',
    months:          'months',
    years:           'years',
    ends:            'Ends',
    every:           'Every',
    repeatOn:        'Repeat on:',
    onDayN:          'On day',
    onTheNth:        'On the',
    whenShort:       'When month is too short:',
    lastDay:         'Use last day of month',
    skipMonth:       'Skip that month',
    syncData:        'Sync',
    reminderNone:    'No reminder',
    reminderAtTime:  'At event time',
    reminder5:       '5 minutes before',
    reminder10:      '10 minutes before',
    reminder15:      '15 minutes before',
    reminder30:      '30 minutes before',
    reminder60:      '1 hour before',
    reminder120:     '2 hours before',
    reminder1440:    '1 day before',
    notifPermTitle:  'Enable Notifications',
    notifPermBody:   'Get reminders for your events. You can turn this off anytime in browser settings.',
    notifPermAllow:  'Allow',
    notifPermSkip:   'Not now',
    currentAccount:  'current',
    onlyAccount:     'only account',
    errEmptyName:    'Please enter an account name.',
    errNameExists:   'An account with this name already exists.',
    errInvalidChars: 'Use only letters, numbers, hyphens, and underscores.',
    hijriYearSuffix: 'AH',
    Fajr: 'Fajr', Sunrise: 'Sunrise', Dhuhr: 'Dhuhr',
    Asr: 'Asr', Maghrib: 'Maghrib', Isha: 'Isha',
    // Prayer UI
    startPrayer:       'Start prayer',
    endPrayer:         'End prayer',
    offsetMin:         'Offset (min)',
    afterBefore:       '+ after · − before',
    eventTimePreview:  'Event time:',
    // Alarm edit screen
    alarmNewTitle:     'New Alarm',
    alarmEditTitle:    'Edit Alarm',
    alarmLabel:        'Label',
    alarmRepeat:       'Repeat',
    alarmSound:        'Sound',
    alarmSnooze:       'Snooze',
    alarmEqTypes:      'Eq. Types',
    alarmCount:        'Count',
    alarmGentleWake:   'Gentle wake',
    alarmGentleDesc:   'Volume ramps up over 30 sec',
    alarmWakeCheck:    'Wake up check',
    alarmWakeDesc:     'Re-fires if not confirmed within 2 min',
    alarmSafetyStop:   'Safety stop',
    alarmSafetyDesc:   'Stop button appears after 5 min',
    alarmEqTimer:      'Equation timer',
    alarmEqTimerDesc:  'Time limit per equation',
    alarmTimerOff:     'Off',
    alarmWallpaper:    'Wallpaper',
    alarmPreview:      'Preview alarm',
    alarmDelete:       'Delete Alarm',
    alarmCustomImg:    'Custom image',
    alarmNoTypes:      'No types selected',
    alarmOneTime:      'One time',
    alarmEveryDay:     'Every day',
    alarmWeekdays:     'Weekdays',
    alarmWeekends:     'Weekends',
    alarmWeekly:       'Weekly',
    alarmSnoozeOff:    'Off',
    alarmSnoozeMin:    'min',
    alarmEqCount:      'equation',
    alarmEqCountPl:    'equations',
    alarmSnoozeLimit:  'Snooze limit',
    alarmSnoozeLimitUnlimited: 'Unlimited',
    alarmSnoozeLimitTimes: 'time',
    alarmSnoozeLimitTimespl: 'times',
    // Equation type picker
    eqTypesTitle:      'Equation Types',
    eqDiffTitle:       'Difficulty',
    eqGroupArith:      'Arithmetic',
    eqGroupAlgebra:    'Algebra',
    eqGroupGeometry:   'Geometry',
    eqGroupOther:      'Other',
    eqAdd:             '+ Add',
    // Difficulty labels
    diffEasy:          'Easy',
    diffMedium:        'Medium',
    diffHard:          'Hard',
    diffVeryHard:      'Very Hard',
    diffExpert:        'Expert',
    // Eq type names
    eqAddSub:          'Addition & Subtraction',
    eqMultiply:        'Multiplication',
    eqDivide:          'Division',
    eqMixedChains:     'Mixed chains',
    eqDiffSquares:     'Difference of squares',
    eqLinearX:         'Solve for x',
    eqAx2:             'ax² = c',
    eqQuadRoots:       'Quadratic (sum of roots)',
    eqQuadVertex:      'Quadratic (vertex)',
    eqExpand:          'Expand brackets',
    eqCubic:           'Cubic roots',
    eqCircleArea:      'Circle area',
    eqArcLength:       'Arc length',
    eqSectorArea:      'Sector area',
    eqChord:           'Chord length',
    eqPercentage:      'Percentages',
    eqComplexAdd:      'Complex +/−',
    eqComplexMul:      'Complex ×',
    eqGroupPhysics:    'Physics',
    eqPhysMotion:      'Motion (v, s, a, t)',
    eqPhysForces:      'Forces (F=ma)',
    eqPhysEnergy:      'Energy (KE, PE, Work)',
    eqPhysElectricity: 'Electricity (V=IR)',
    eqPhysGraphs:      'Motion Graphs',
    eqPhysPressure:    'Pressure & Density',
    // Alarms list
    alarmsTitle:       'Alarms',
    alarmOnce:         'Once',
    alarmConfigureAlarm: 'Configure alarm…',
    prev:            'Prev',
    next:            'Next',
    hijriMonths: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    hijriMonthNames: ['Muharram','Safar',"Rabi' al-awwal","Rabi' al-thani","Jumada al-awwal","Jumada al-thani",'Rajab',"Sha'ban",'Ramadan','Shawwal',"Dhu al-Qi'dah",'Dhu al-Hijjah'],
  },
  ar: {
    monthNames:      ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
    monthNamesShort: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
    dayNamesLong:    ['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],
    dayNamesShort:   ['أحد','اثنين','ثلاثاء','أربعاء','خميس','جمعة','سبت'],
    dayLetters:      ['ح','ن','ث','ر','خ','ج','س'],
    newEvent:        'حدث جديد',
    addCalendar:     'إضافة تقويم',
    myCalendars:     'تقاويمي',
    accountSettings: 'الحساب والإعدادات',
    today:           'اليوم',
    openJournal:     'فتح اليومية',
    hideJournal:     'إخفاء اليومية',
    journal:         'اليومية',
    score:           'النقاط',
    tasks:           'المهام',
    day:             'يوم',
    week:            'أسبوع',
    threeDays:       '٣ أيام',
    month:           'شهر',
    year:            'سنة',
    allTime:         'الكل',
    prayerTimes:     'أوقات الصلاة',
    hidePrayerTimes: 'إخفاء أوقات الصلاة',
    saveJournal:     'حفظ اليومية',
    saveScore:       'حفظ النقاط',
    save:            'حفظ',
    cancel:          'إلغاء',
    delete:          'حذف',
    newTaskPlaceholder: 'مهمة جديدة…',
    allDay:          'طوال اليوم',
    doesNotRepeat:   'لا تتكرر',
    daily:           'يومياً',
    weekly:          'أسبوعياً',
    monthly:         'شهرياً',
    yearly:          'سنوياً',
    weekdays:        'كل يوم عمل',
    custom:          'مخصص...',
    add:             'إضافة',
    profilePicture:  'الصورة الشخصية',
    appearance:      'المظهر والثيمات',
    journalVars:     'متغيرات اليومية',
    locationSettings:'إعدادات الموقع',
    backgroundImage: 'صورة الخلفية',
    renderWindow:    'نافذة عرض الأحداث',
    viewAllTasks:    'عرض جميع المهام',
    forgottenTasks:  'المهام المنسية',
    exportJson:      'تصدير البيانات (JSON)',
    exportIcs:       'تصدير للتقويم (.ics)',
    importData:      'استيراد البيانات',
    clearData:       'مسح جميع البيانات',
    accounts:        'الحسابات',
    settings:        'الإعدادات',
    navMenu:         'القائمة',
    navAdd:          'إضافة',
    navPrayer:       'الصلاة',
    toHijri:         'التحويل للتقويم الهجري',
    toGregorian:     'التحويل للتقويم الميلادي',
    pts:             'نقطة',
    writePlaceholder:'اكتب عن يومك…',
    titlePlaceholder:'العنوان (اختياري)',
    addTitle:        'أضف عنواناً',
    pointsPlaceholder:'النقاط (اختياري)',
    addDescription:  'أضف وصفاً',
    timeTo:          'إلى',
    edit:            'تعديل',
    close:           'إغلاق',
    contd:           'تابع',
    usePrayerTimes:  'استخدام أوقات الصلاة',
    prayerTime:      'وقت الصلاة',
    startOffset:     'إزاحة البداية (دقائق)',
    endOffset:       'إزاحة النهاية (دقائق)',
    switchToArabic:  'العربية',
    switchToEnglish: 'English',
    newCalendar:     'تقويم جديد',
    editCalendar:    'تعديل التقويم',
    editEvent:       'تعديل الحدث',
    deleteCalendar:  'حذف التقويم',
    jumuah:          'الجمعة',
    adjusted:        'معدّل',
    sighting:        'رؤية الهلال',
    moonSighting:    'رؤية الهلال',
    addAccount:      'إضافة حساب',
    deleteAccount:   'حذف حساب',
    upload:          'رفع',
    remove:          'إزالة',
    search:          'ابحث عن أحداث…',
    variables:       'المتغيرات',
    noneSet:         'لا يوجد',
    expression:      'التعبير',
    never:           'أبداً',
    after:           'بعد',
    onDate:          'في',
    on:              'في',
    times:           'مرات',
    occurrences:     'مرات',
    days:            'أيام',
    weeks:           'أسابيع',
    months:          'أشهر',
    years:           'سنوات',
    ends:            'تنتهي',
    every:           'كل',
    repeatOn:        'تكرار في:',
    onDayN:          'في اليوم',
    onTheNth:        'في ال',
    whenShort:       'عند قِصَر الشهر:',
    lastDay:         'استخدم آخر يوم',
    skipMonth:       'تخطَّ الشهر',
    syncData:        'مزامنة',
    reminderNone:    'بدون تذكير',
    reminderAtTime:  'عند وقت الحدث',
    reminder5:       'قبل 5 دقائق',
    reminder10:      'قبل 10 دقائق',
    reminder15:      'قبل 15 دقيقة',
    reminder30:      'قبل 30 دقيقة',
    reminder60:      'قبل ساعة',
    reminder120:     'قبل ساعتين',
    reminder1440:    'قبل يوم',
    notifPermTitle:  'تفعيل الإشعارات',
    notifPermBody:   'احصل على تذكيرات لأحداثك. يمكنك إيقافها في أي وقت من إعدادات المتصفح.',
    notifPermAllow:  'السماح',
    notifPermSkip:   'ليس الآن',
    currentAccount:  'الحالي',
    onlyAccount:     'حساب وحيد',
    errEmptyName:    'يرجى إدخال اسم الحساب.',
    errNameExists:   'يوجد حساب بهذا الاسم بالفعل.',
    errInvalidChars: 'استخدم حروفاً وأرقاماً وشرطات فقط.',
    hijriYearSuffix: 'هـ',
    Fajr: 'الفجر', Sunrise: 'الشروق', Dhuhr: 'الظهر',
    Asr: 'العصر', Maghrib: 'المغرب', Isha: 'العشاء',
    // Prayer UI
    startPrayer:       'صلاة البداية',
    endPrayer:         'صلاة النهاية',
    offsetMin:         'الإزاحة (دقيقة)',
    afterBefore:       '+ بعد · − قبل',
    eventTimePreview:  'وقت الحدث:',
    // Alarm edit screen
    alarmNewTitle:     'منبّه جديد',
    alarmEditTitle:    'تعديل المنبّه',
    alarmLabel:        'الاسم',
    alarmRepeat:       'التكرار',
    alarmSound:        'الصوت',
    alarmSnooze:       'الغفوة',
    alarmEqTypes:      'أنواع المعادلات',
    alarmCount:        'العدد',
    alarmGentleWake:   'إيقاظ تدريجي',
    alarmGentleDesc:   'يرتفع الصوت تدريجياً خلال ٣٠ ثانية',
    alarmWakeCheck:    'التحقق من الاستيقاظ',
    alarmWakeDesc:     'يُعيد الرنين إذا لم يُؤكَّد خلال دقيقتين',
    alarmSafetyStop:   'إيقاف الطوارئ',
    alarmSafetyDesc:   'زر الإيقاف يظهر بعد ٥ دقائق',
    alarmEqTimer:      'مؤقت المعادلة',
    alarmEqTimerDesc:  'حد زمني لكل معادلة',
    alarmTimerOff:     'إيقاف',
    alarmWallpaper:    'خلفية المنبّه',
    alarmPreview:      'معاينة المنبّه',
    alarmDelete:       'حذف المنبّه',
    alarmCustomImg:    'صورة مخصصة',
    alarmNoTypes:      'لم تُختَر أنواع',
    alarmOneTime:      'مرة واحدة',
    alarmEveryDay:     'كل يوم',
    alarmWeekdays:     'أيام الأسبوع',
    alarmWeekends:     'عطلة نهاية الأسبوع',
    alarmWeekly:       'أسبوعياً',
    alarmSnoozeOff:    'إيقاف',
    alarmSnoozeMin:    'دقيقة',
    alarmEqCount:      'معادلة',
    alarmEqCountPl:    'معادلات',
    alarmSnoozeLimit:  'حد الغفوة',
    alarmSnoozeLimitUnlimited: 'غير محدود',
    alarmSnoozeLimitTimes: 'مرة',
    alarmSnoozeLimitTimespl: 'مرات',
    // Equation type picker
    eqTypesTitle:      'أنواع المعادلات',
    eqDiffTitle:       'الصعوبة',
    eqGroupArith:      'حسابيات',
    eqGroupAlgebra:    'جبر',
    eqGroupGeometry:   'هندسة',
    eqGroupOther:      'أخرى',
    eqAdd:             '+ إضافة',
    // Difficulty labels
    diffEasy:          'سهل',
    diffMedium:        'متوسط',
    diffHard:          'صعب',
    diffVeryHard:      'صعب جداً',
    diffExpert:        'خبير',
    // Eq type names
    eqAddSub:          'جمع وطرح',
    eqMultiply:        'ضرب',
    eqDivide:          'قسمة',
    eqMixedChains:     'سلاسل مختلطة',
    eqDiffSquares:     'فرق المربعات',
    eqLinearX:         'حل معادلة من الدرجة الأولى',
    eqAx2:             'ax² = c',
    eqQuadRoots:       'معادلة تربيعية (مجموع الجذور)',
    eqQuadVertex:      'معادلة تربيعية (الرأس)',
    eqExpand:          'ضرب قوسين',
    eqCubic:           'جذور المعادلة التكعيبية',
    eqCircleArea:      'مساحة الدائرة',
    eqArcLength:       'طول القوس',
    eqSectorArea:      'مساحة القطاع',
    eqChord:           'طول الوتر',
    eqPercentage:      'نسب مئوية',
    eqComplexAdd:      'أعداد مركبة +/−',
    eqComplexMul:      'أعداد مركبة ×',
    eqGroupPhysics:    'فيزياء',
    eqPhysMotion:      'الحركة (ع، م، ت، ز)',
    eqPhysForces:      'القوى (ق=ك×ت)',
    eqPhysEnergy:      'الطاقة (حركية، وضع، شغل)',
    eqPhysElectricity: 'الكهرباء (ج=ت×م)',
    eqPhysGraphs:      'رسوم الحركة البيانية',
    eqPhysPressure:    'الضغط والكثافة',
    // Alarms list
    alarmsTitle:       'المنبّهات',
    alarmOnce:         'مرة واحدة',
    alarmConfigureAlarm: 'إعداد المنبّه…',
    prev:            'السابق',
    next:            'التالي',
    hijriMonthNames: ['محرم','صفر','ربيع الأول','ربيع الآخر','جمادى الأولى','جمادى الآخرة','رجب','شعبان','رمضان','شوال','ذو القعدة','ذو الحجة'],
    monthNamesShort: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  }
};

function tHijri(hm) {
    // hm is 1-based Hijri month index
    const names = (TRANSLATIONS[state.language] || TRANSLATIONS.en).hijriMonthNames;
    return names ? names[hm - 1] : (TRANSLATIONS.en.hijriMonthNames[hm - 1]);
}

function t(key) {
    return (TRANSLATIONS[state.language] || TRANSLATIONS.en)[key] || key;
}

function saveLanguage() { localStorage.setItem(STORAGE_KEYS.LANGUAGE, state.language); }
function loadLanguage() { state.language = localStorage.getItem(STORAGE_KEYS.LANGUAGE) || 'en'; }

function toggleLanguage() {
    state.language = state.language === 'en' ? 'ar' : 'en';
    saveLanguage();
    applyLanguage();
    closeAccountSettings();
    updateWidgetData();
}

function applyLanguage() {
    const isAr = state.language === 'ar';
    const html = document.documentElement;
    html.setAttribute('lang', isAr ? 'ar' : 'en');
    // We do NOT set dir=rtl on html — that would flip flex layouts.
    // Instead we use a body class and apply RTL only to text content.
    if (isAr) {
        document.body.classList.add('lang-ar');
        document.body.classList.remove('lang-en');
    } else {
        document.body.classList.remove('lang-ar');
        document.body.classList.add('lang-en');
    }

    // Load Arabic font once
    const fontId = 'arabic-font-link';
    if (isAr && !document.getElementById(fontId)) {
        const link = document.createElement('link');
        link.id = fontId;
        link.rel = 'stylesheet';
        link.href = 'https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700&display=swap';
        document.head.appendChild(link);
    }

    // Close any open dynamically-created modals so they re-render with correct language
    // NOTE: renderWindowModal and forgottenTasksModal are static HTML — only hide them, don't remove!
    ['locationModal','themePickerModal','variableSettingsModal','accountSettingsPanel',
     'viewAllTasksModal','hijriSightingPanel']
        .forEach(id => document.getElementById(id)?.remove());
    hideEl('renderWindowModal');
    hideEl('forgottenTasksModal');

    // Patch static HTML elements via data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const val = t(key);
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            el.placeholder = val;
        } else if (el.tagName === 'OPTION') {
            el.textContent = val;
        } else {
            el.textContent = val;
        }
    });

    // Re-render everything
    renderCurrentView();
    renderMiniCalendar();
    renderCalendarList();
}


// Extended Color Palette
const CALENDAR_COLORS = [
    { id: 'blue',   name: 'Blue',   bg: 'bg-blue-500',   light: 'bg-blue-100',   dark: 'bg-blue-900/30',   text: 'text-blue-800',   darkText: 'text-blue-200',   hex: '#3b82f6' },
    { id: 'purple', name: 'Purple', bg: 'bg-purple-500', light: 'bg-purple-100', dark: 'bg-purple-900/30', text: 'text-purple-800', darkText: 'text-purple-200', hex: '#8b5cf6' },
    { id: 'green',  name: 'Green',  bg: 'bg-green-500',  light: 'bg-green-100',  dark: 'bg-green-900/30',  text: 'text-green-800',  darkText: 'text-green-200',  hex: '#10b981' },
    { id: 'orange', name: 'Orange', bg: 'bg-orange-500', light: 'bg-orange-100', dark: 'bg-orange-900/30', text: 'text-orange-800', darkText: 'text-orange-200', hex: '#f59e0b' },
    { id: 'red',    name: 'Red',    bg: 'bg-red-500',    light: 'bg-red-100',    dark: 'bg-red-900/30',    text: 'text-red-800',    darkText: 'text-red-200',    hex: '#ef4444' },
    { id: 'pink',   name: 'Pink',   bg: 'bg-pink-500',   light: 'bg-pink-100',   dark: 'bg-pink-900/30',   text: 'text-pink-800',   darkText: 'text-pink-200',   hex: '#ec4899' },
    { id: 'yellow', name: 'Yellow', bg: 'bg-yellow-500', light: 'bg-yellow-100', dark: 'bg-yellow-900/30', text: 'text-yellow-800', darkText: 'text-yellow-200', hex: '#eab308' },
    { id: 'teal',   name: 'Teal',   bg: 'bg-teal-500',   light: 'bg-teal-100',   dark: 'bg-teal-900/30',   text: 'text-teal-800',   darkText: 'text-teal-200',   hex: '#14b8a6' },
    { id: 'indigo', name: 'Indigo', bg: 'bg-indigo-500', light: 'bg-indigo-100', dark: 'bg-indigo-900/30', text: 'text-indigo-800', darkText: 'text-indigo-200', hex: '#6366f1' },
    { id: 'cyan',   name: 'Cyan',   bg: 'bg-cyan-500',   light: 'bg-cyan-100',   dark: 'bg-cyan-900/30',   text: 'text-cyan-800',   darkText: 'text-cyan-200',   hex: '#06b6d4' },
    { id: 'lime',   name: 'Lime',   bg: 'bg-lime-500',   light: 'bg-lime-100',   dark: 'bg-lime-900/30',   text: 'text-lime-800',   darkText: 'text-lime-200',   hex: '#84cc16' },
    { id: 'gray',   name: 'Gray',   bg: 'bg-gray-500',   light: 'bg-gray-100',   dark: 'bg-gray-900/30',   text: 'text-gray-800',   darkText: 'text-gray-200',   hex: '#6b7280' }
];

// Default Calendars
const DEFAULT_CALENDARS = [
    { id: 'personal',  name: 'Personal',  color: 'blue'   },
    { id: 'work',      name: 'Work',      color: 'purple' },
    { id: 'reminders', name: 'Reminders', color: 'orange' }
];

// Prayer Names
const PRAYER_NAMES = ['Fajr', 'Sunrise', 'Dhuhr', 'Asr', 'Maghrib', 'Isha'];

// APPEARANCE THEMES (Discord-style presets)
// Each theme is a set of CSS variable overrides applied to :root / .dark
const THEME_NAMES_AR = {
    'default':      { name: '\u0627\u0641\u062a\u0631\u0627\u0636\u064a',      description: '\u0623\u0628\u064a\u0636 \u0646\u0638\u064a\u0641 \u0648\u062f\u0627\u0643\u0646' },
    'discord':      { name: '\u062f\u064a\u0633\u0643\u0648\u0631\u062f',      description: '\u0631\u0645\u0627\u062f\u064a-\u0623\u0632\u0631\u0642 \u062f\u0627\u0643\u0646' },
    'midnight':     { name: '\u0645\u0646\u062a\u0635\u0641 \u0627\u0644\u0644\u064a\u0644',  description: '\u0632\u0631\u0642\u0629 \u062f\u0627\u0643\u0646\u0629 \u0639\u0645\u064a\u0642\u0629' },
    'forest':       { name: '\u0627\u0644\u063a\u0627\u0628\u0629',       description: '\u0623\u0644\u0648\u0627\u0646 \u062e\u0636\u0631\u0627\u0621 \u0637\u0628\u064a\u0639\u064a\u0629' },
    'sunset':       { name: '\u0627\u0644\u063a\u0631\u0648\u0628',       description: '\u0628\u0631\u062a\u0642\u0627\u0644\u064a \u0648\u0628\u0646\u0641\u0633\u062c\u064a \u062f\u0627\u0641\u0626' },
    'rose':         { name: '\u0627\u0644\u0648\u0631\u062f',        description: '\u0648\u0631\u062f\u064a \u0646\u0627\u0639\u0645' },
    'slate':        { name: '\u0627\u0644\u0635\u062e\u0631',        description: '\u0631\u0645\u0627\u062f\u064a \u0628\u0627\u0631\u062f' },
    'crimson_moon': { name: '\u0627\u0644\u0642\u0645\u0631 \u0627\u0644\u0642\u0631\u0645\u0632\u064a', description: '\u0623\u062d\u0645\u0631 \u063a\u0627\u0645\u0642 \u0648\u0628\u0646\u0641\u0633\u062c\u064a \u062f\u0627\u0643\u0646' },
    'chroma_glow':  { name: '\u0648\u0647\u062c \u0627\u0644\u0623\u0644\u0648\u0627\u0646',  description: '\u062a\u062f\u0631\u062c \u0646\u064a\u0648\u0646 \u0643\u0647\u0631\u0628\u0627\u0626\u064a' },
    'sakura':       { name: '\u0632\u0647\u0631 \u0627\u0644\u0643\u0631\u0632',    description: '\u0648\u0631\u062f\u064a \u0632\u0647\u0631\u064a \u0646\u0627\u0639\u0645' },
    'aurora':       { name: '\u0627\u0644\u0623\u0648\u0631\u0648\u0631\u0627',     description: '\u0623\u062e\u0636\u0631 \u0648\u0632\u0645\u0631\u062f\u064a \u0634\u0645\u0627\u0644\u064a' },
    'golden_hour':  { name: '\u0627\u0644\u0633\u0627\u0639\u0629 \u0627\u0644\u0630\u0647\u0628\u064a\u0629', description: '\u0639\u0646\u0628\u0631 \u0648\u0630\u0647\u0628 \u0648\u0628\u0646\u064a \u0639\u0645\u064a\u0642' },
};

const THEMES = [
    {
        id: 'default',
        name: 'Default',
        description: 'Clean white & dark',
        preview: ['#ffffff', '#0f0f0f', '#3b82f6'],
        light: {},
        dark: {}
    },
    {
        id: 'discord',
        name: 'Discord',
        description: 'Discord dark blue-grey',
        preview: ['#36393f', '#2f3136', '#5865f2'],
        light: {
            '--bg-primary':   '#ffffff',
            '--bg-secondary': '#f2f3f5',
            '--bg-tertiary':  '#e3e5e8',
            '--text-primary': '#2e3338',
            '--text-secondary': '#747f8d',
            '--border-color': '#dcddde',
            '--accent':       '#5865f2',
            '--bg-panel':           'rgba(255,255,255,0.93)',
            '--bg-panel-secondary': 'rgba(242,243,245,0.93)',
        },
        dark: {
            '--bg-primary':   '#36393f',
            '--bg-secondary': '#2f3136',
            '--bg-tertiary':  '#202225',
            '--text-primary': '#dcddde',
            '--text-secondary': '#96989d',
            '--border-color': '#40444b',
            '--accent':       '#5865f2',
            '--bg-panel':           'rgba(54,57,63,0.93)',
            '--bg-panel-secondary': 'rgba(47,49,54,0.93)',
        }
    },
    {
        id: 'midnight',
        name: 'Midnight',
        description: 'Deep blue darkness',
        preview: ['#0d1117', '#161b22', '#58a6ff'],
        light: {
            '--bg-primary':   '#f0f6ff',
            '--bg-secondary': '#e6f0fa',
            '--bg-tertiary':  '#d0e4f7',
            '--text-primary': '#0d1117',
            '--text-secondary': '#586069',
            '--border-color': '#c8d8e8',
            '--accent':       '#0969da',
            '--bg-panel':           'rgba(240,246,255,0.93)',
            '--bg-panel-secondary': 'rgba(230,240,250,0.93)',
        },
        dark: {
            '--bg-primary':   '#0d1117',
            '--bg-secondary': '#161b22',
            '--bg-tertiary':  '#21262d',
            '--text-primary': '#c9d1d9',
            '--text-secondary': '#8b949e',
            '--border-color': '#30363d',
            '--accent':       '#58a6ff',
            '--bg-panel':           'rgba(13,17,23,0.93)',
            '--bg-panel-secondary': 'rgba(22,27,34,0.93)',
        }
    },
    {
        id: 'forest',
        name: 'Forest',
        description: 'Natural greens',
        preview: ['#1a2e1a', '#243324', '#4caf50'],
        light: {
            '--bg-primary':   '#f1f8f1',
            '--bg-secondary': '#e8f5e9',
            '--bg-tertiary':  '#dcedc8',
            '--text-primary': '#1b2e1b',
            '--text-secondary': '#558b55',
            '--border-color': '#c5e1a5',
            '--accent':       '#388e3c',
            '--bg-panel':           'rgba(241,248,241,0.93)',
            '--bg-panel-secondary': 'rgba(232,245,233,0.93)',
        },
        dark: {
            '--bg-primary':   '#1a2e1a',
            '--bg-secondary': '#1e331e',
            '--bg-tertiary':  '#243824',
            '--text-primary': '#c8e6c9',
            '--text-secondary': '#81c784',
            '--border-color': '#2e4a2e',
            '--accent':       '#66bb6a',
            '--bg-panel':           'rgba(26,46,26,0.93)',
            '--bg-panel-secondary': 'rgba(30,51,30,0.93)',
        }
    },
    {
        id: 'sunset',
        name: 'Sunset',
        description: 'Warm oranges & purples',
        preview: ['#2d1b33', '#3d2040', '#ff6b35'],
        light: {
            '--bg-primary':   '#fff8f3',
            '--bg-secondary': '#fff0e6',
            '--bg-tertiary':  '#fde0cc',
            '--text-primary': '#2d1b00',
            '--text-secondary': '#8b5e3c',
            '--border-color': '#f5c9a0',
            '--accent':       '#e65100',
            '--bg-panel':           'rgba(255,248,243,0.93)',
            '--bg-panel-secondary': 'rgba(255,240,230,0.93)',
        },
        dark: {
            '--bg-primary':   '#2d1b33',
            '--bg-secondary': '#3d2040',
            '--bg-tertiary':  '#4a2550',
            '--text-primary': '#f5d0b5',
            '--text-secondary': '#cc9977',
            '--border-color': '#5a3060',
            '--accent':       '#ff6b35',
            '--bg-panel':           'rgba(45,27,51,0.93)',
            '--bg-panel-secondary': 'rgba(61,32,64,0.93)',
        }
    },
    {
        id: 'rose',
        name: 'Rose',
        description: 'Soft pinks & roses',
        preview: ['#2d1b22', '#3d2030', '#f43f5e'],
        light: {
            '--bg-primary':   '#fff5f7',
            '--bg-secondary': '#ffe4ea',
            '--bg-tertiary':  '#ffd1da',
            '--text-primary': '#2d1b22',
            '--text-secondary': '#9d5065',
            '--border-color': '#fbb6c6',
            '--accent':       '#e11d48',
            '--bg-panel':           'rgba(255,245,247,0.93)',
            '--bg-panel-secondary': 'rgba(255,228,234,0.93)',
        },
        dark: {
            '--bg-primary':   '#1c0f14',
            '--bg-secondary': '#271419',
            '--bg-tertiary':  '#32191f',
            '--text-primary': '#fce7ed',
            '--text-secondary': '#d4899a',
            '--border-color': '#4a1e28',
            '--accent':       '#fb7185',
            '--bg-panel':           'rgba(28,15,20,0.93)',
            '--bg-panel-secondary': 'rgba(39,20,25,0.93)',
        }
    },
    {
        id: 'slate',
        name: 'Slate',
        description: 'Cool slate greys',
        preview: ['#1e293b', '#0f172a', '#94a3b8'],
        light: {
            '--bg-primary':   '#f8fafc',
            '--bg-secondary': '#f1f5f9',
            '--bg-tertiary':  '#e2e8f0',
            '--text-primary': '#0f172a',
            '--text-secondary': '#64748b',
            '--border-color': '#cbd5e1',
            '--accent':       '#3b82f6',
            '--bg-panel':           'rgba(248,250,252,0.93)',
            '--bg-panel-secondary': 'rgba(241,245,249,0.93)',
        },
        dark: {
            '--bg-primary':   '#0f172a',
            '--bg-secondary': '#1e293b',
            '--bg-tertiary':  '#334155',
            '--text-primary': '#e2e8f0',
            '--text-secondary': '#94a3b8',
            '--border-color': '#475569',
            '--accent':       '#38bdf8',
            '--bg-panel':           'rgba(15,23,42,0.93)',
            '--bg-panel-secondary': 'rgba(30,41,59,0.93)',
        }
    },
    {
        id: 'crimson_moon',
        name: 'Crimson Moon',
        description: 'Deep red & dark purple',
        gradient: true,
        preview: ['#1a0a1e', '#3d0c1a', '#ff2d55'],
        light: {
            '--bg-primary':   '#1a0a1e',
            '--bg-secondary': '#26102a',
            '--bg-tertiary':  '#32153a',
            '--text-primary': '#fce4ec',
            '--text-secondary': '#f48fb1',
            '--border-color': '#4a1040',
            '--accent':       '#ff2d55',
            '--bg-panel':           'rgba(26,10,30,0.92)',
            '--bg-panel-secondary': 'rgba(38,16,42,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#1a0a1e 0%,#2d0a2a 50%,#3d0c1a 100%)',
            '--header-gradient':    'linear-gradient(90deg,#1a0a1e 0%,#2d0c28 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#ff2d55,#bf0a5e)',
        },
        dark: {
            '--bg-primary':   '#0f0612',
            '--bg-secondary': '#1a0a1e',
            '--bg-tertiary':  '#26102a',
            '--text-primary': '#fce4ec',
            '--text-secondary': '#f48fb1',
            '--border-color': '#3d0c30',
            '--accent':       '#ff2d55',
            '--bg-panel':           'rgba(15,6,18,0.92)',
            '--bg-panel-secondary': 'rgba(26,10,30,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#0f0612 0%,#1e082a 50%,#2d0a1e 100%)',
            '--header-gradient':    'linear-gradient(90deg,#0f0612 0%,#1e0a1e 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#ff2d55,#ff6b9d)',
        }
    },
    {
        id: 'chroma_glow',
        name: 'Chroma Glow',
        description: 'Electric neon gradient',
        gradient: true,
        preview: ['#0a0a1a', '#1a0a3a', '#00d4ff'],
        light: {
            '--bg-primary':   '#0a0a1a',
            '--bg-secondary': '#0f0f28',
            '--bg-tertiary':  '#161635',
            '--text-primary': '#e0f7ff',
            '--text-secondary': '#7dd3fc',
            '--border-color': '#1e2048',
            '--accent':       '#00d4ff',
            '--bg-panel':           'rgba(10,10,26,0.92)',
            '--bg-panel-secondary': 'rgba(15,15,40,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#0a0a1a 0%,#0d0a2e 40%,#1a0a3a 100%)',
            '--header-gradient':    'linear-gradient(90deg,#0a0a1a 0%,#100a2e 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#00d4ff,#a855f7,#ff2d55)',
        },
        dark: {
            '--bg-primary':   '#06060f',
            '--bg-secondary': '#0a0a1a',
            '--bg-tertiary':  '#0f0f28',
            '--text-primary': '#e0f7ff',
            '--text-secondary': '#7dd3fc',
            '--border-color': '#151535',
            '--accent':       '#00d4ff',
            '--bg-panel':           'rgba(6,6,15,0.92)',
            '--bg-panel-secondary': 'rgba(10,10,26,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#06060f 0%,#0a0620 40%,#10062e 100%)',
            '--header-gradient':    'linear-gradient(90deg,#06060f 0%,#0a0820 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#00d4ff,#a855f7,#ff2d55)',
        }
    },
    {
        id: 'sakura',
        name: 'Sakura',
        description: 'Soft cherry blossom pinks',
        gradient: true,
        preview: ['#1a0a14', '#2d1020', '#ff8fab'],
        light: {
            '--bg-primary':   '#fff0f5',
            '--bg-secondary': '#ffe4ef',
            '--bg-tertiary':  '#ffd6e8',
            '--text-primary': '#2d0a1e',
            '--text-secondary': '#9d4067',
            '--border-color': '#fbb6ce',
            '--accent':       '#e91e8c',
            '--bg-panel':           'rgba(255,240,245,0.93)',
            '--bg-panel-secondary': 'rgba(255,228,239,0.93)',
            '--sidebar-gradient':   'linear-gradient(160deg,#fff0f5 0%,#ffe0ee 60%,#ffd0e8 100%)',
            '--header-gradient':    'linear-gradient(90deg,#fff0f5 0%,#ffe8f2 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#e91e8c,#f06292)',
        },
        dark: {
            '--bg-primary':   '#1a0a14',
            '--bg-secondary': '#240e1c',
            '--bg-tertiary':  '#2e1226',
            '--text-primary': '#fce4ec',
            '--text-secondary': '#f48fb1',
            '--border-color': '#4a1436',
            '--accent':       '#ff8fab',
            '--bg-panel':           'rgba(26,10,20,0.92)',
            '--bg-panel-secondary': 'rgba(36,14,28,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#1a0a14 0%,#220c1a 50%,#2d1020 100%)',
            '--header-gradient':    'linear-gradient(90deg,#1a0a14 0%,#220e18 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#ff8fab,#f48fb1)',
        }
    },
    {
        id: 'aurora',
        name: 'Aurora',
        description: 'Northern lights greens & teals',
        gradient: true,
        preview: ['#061a12', '#0a2a1e', '#00e5a0'],
        light: {
            '--bg-primary':   '#f0faf5',
            '--bg-secondary': '#e0f5ec',
            '--bg-tertiary':  '#c8eedd',
            '--text-primary': '#062012',
            '--text-secondary': '#2e7d55',
            '--border-color': '#a8d8be',
            '--accent':       '#00897b',
            '--bg-panel':           'rgba(240,250,245,0.93)',
            '--bg-panel-secondary': 'rgba(224,245,236,0.93)',
            '--sidebar-gradient':   'linear-gradient(160deg,#f0faf5 0%,#e0f7ee 60%,#c8f0de 100%)',
            '--header-gradient':    'linear-gradient(90deg,#f0faf5 0%,#dff5ea 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#00897b,#26c6da)',
        },
        dark: {
            '--bg-primary':   '#061a12',
            '--bg-secondary': '#0a2a1e',
            '--bg-tertiary':  '#0e3a28',
            '--text-primary': '#ccf2e0',
            '--text-secondary': '#52c792',
            '--border-color': '#144a28',
            '--accent':       '#00e5a0',
            '--bg-panel':           'rgba(6,26,18,0.92)',
            '--bg-panel-secondary': 'rgba(10,42,30,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#061a12 0%,#082a18 50%,#0a3020 100%)',
            '--header-gradient':    'linear-gradient(90deg,#061a12 0%,#082018 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#00e5a0,#00bcd4)',
        }
    },
    {
        id: 'golden_hour',
        name: 'Golden Hour',
        description: 'Warm amber, gold & deep brown',
        gradient: true,
        preview: ['#1a1000', '#2e1a00', '#ffa000'],
        light: {
            '--bg-primary':   '#fffbf0',
            '--bg-secondary': '#fff3d6',
            '--bg-tertiary':  '#ffe8b0',
            '--text-primary': '#1a1000',
            '--text-secondary': '#8a6000',
            '--border-color': '#f5d060',
            '--accent':       '#f59e0b',
            '--bg-panel':           'rgba(255,251,240,0.93)',
            '--bg-panel-secondary': 'rgba(255,243,214,0.93)',
            '--sidebar-gradient':   'linear-gradient(160deg,#fffbf0 0%,#fff3d0 60%,#ffe8a8 100%)',
            '--header-gradient':    'linear-gradient(90deg,#fffbf0 0%,#fff0c8 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#f59e0b,#ef4444)',
        },
        dark: {
            '--bg-primary':   '#1a1000',
            '--bg-secondary': '#261800',
            '--bg-tertiary':  '#332000',
            '--text-primary': '#fef3c7',
            '--text-secondary': '#fbbf24',
            '--border-color': '#3d2800',
            '--accent':       '#ffa000',
            '--bg-panel':           'rgba(26,16,0,0.92)',
            '--bg-panel-secondary': 'rgba(38,24,0,0.92)',
            '--sidebar-gradient':   'linear-gradient(160deg,#1a1000 0%,#221400 50%,#2e1a00 100%)',
            '--header-gradient':    'linear-gradient(90deg,#1a1000 0%,#221600 100%)',
            '--accent-gradient':    'linear-gradient(90deg,#ffa000,#ff6f00)',
        }
    }
];

// State Management
